"""add client model

Revision ID: 8eb94748e6cc
Revises: 
Create Date: 2026-06-17 00:38:13.157870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb94748e6cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('discrepancies', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_discrepancies_client_id'), 'discrepancies', ['client_id'], unique=False)
    op.create_foreign_key(None, 'discrepancies', 'clients', ['client_id'], ['id'])
    op.add_column('quickbooks_entries', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_quickbooks_entries_client_id'), 'quickbooks_entries', ['client_id'], unique=False)
    op.create_foreign_key(None, 'quickbooks_entries', 'clients', ['client_id'], ['id'])
    op.add_column('shopify_orders', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_shopify_orders_client_id'), 'shopify_orders', ['client_id'], unique=False)
    op.create_foreign_key(None, 'shopify_orders', 'clients', ['client_id'], ['id'])
    op.add_column('stripe_transactions', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stripe_transactions_client_id'), 'stripe_transactions', ['client_id'], unique=False)
    op.create_foreign_key(None, 'stripe_transactions', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stripe_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_stripe_transactions_client_id'), table_name='stripe_transactions')
    op.drop_column('stripe_transactions', 'client_id')
    op.drop_constraint(None, 'shopify_orders', type_='foreignkey')
    op.drop_index(op.f('ix_shopify_orders_client_id'), table_name='shopify_orders')
    op.drop_column('shopify_orders', 'client_id')
    op.drop_constraint(None, 'quickbooks_entries', type_='foreignkey')
    op.drop_index(op.f('ix_quickbooks_entries_client_id'), table_name='quickbooks_entries')
    op.drop_column('quickbooks_entries', 'client_id')
    op.drop_constraint(None, 'discrepancies', type_='foreignkey')
    op.drop_index(op.f('ix_discrepancies_client_id'), table_name='discrepancies')
    op.drop_column('discrepancies', 'client_id')
    op.drop_table('clients')
    # ### end Alembic commands ###
